import {
    FaBookOpen,
    FaDesktop,
    FaMicrochip,
    FaCode,
    FaProjectDiagram,
    FaSitemap,
    FaDatabase,
    FaNetworkWired,
    FaBroadcastTower,
    FaWindows,
    FaLinux,
    FaMemory,
    FaCogs,
    FaSquareRootAlt,
    FaGlobe,
    FaWifi,
    FaShieldAlt,
    FaCloud,
    FaLock,
    FaServer,
    FaCodeBranch,
    FaBrain,
    FaShoppingCart,
    FaBolt,
    FaQuestionCircle,
    FaUniversity,
    FaCalculator,
    FaBook,
    FaLanguage,
    FaLightbulb,
} from "react-icons/fa";

export const subjectIconMap = {
    FaBookOpen: <FaBookOpen size={20} />,
    FaDesktop: <FaDesktop size={20} />,
    FaMicrochip: <FaMicrochip size={20} />,
    FaCode: <FaCode size={20} />,
    FaProjectDiagram: <FaProjectDiagram size={20} />,
    FaSitemap: <FaSitemap size={20} />,
    FaDatabase: <FaDatabase size={20} />,
    FaNetworkWired: <FaNetworkWired size={20} />,
    FaBroadcastTower: <FaBroadcastTower size={20} />,
    FaWindows: <FaWindows size={20} />,
    FaLinux: <FaLinux size={20} />,
    FaMemory: <FaMemory size={20} />,
    FaCogs: <FaCogs size={20} />,
    FaSquareRootAlt: <FaSquareRootAlt size={20} />,
    FaGlobe: <FaGlobe size={20} />,
    FaWifi: <FaWifi size={20} />,
    FaShieldAlt: <FaShieldAlt size={20} />,
    FaCloud: <FaCloud size={20} />,
    FaLock: <FaLock size={20} />,
    FaServer: <FaServer size={20} />,
    FaCodeBranch: <FaCodeBranch size={20} />,
    FaBrain: <FaBrain size={20} />,
    FaShoppingCart: <FaShoppingCart size={20} />,
    FaBolt: <FaBolt size={20} />,
    FaQuestionCircle: <FaQuestionCircle size={20} />,
    FaUniversity: <FaUniversity size={20} />,
    FaCalculator: <FaCalculator size={20} />,
    FaBook: <FaBook size={20} />,
    FaLanguage: <FaLanguage size={20} />,
    FaLightbulb: <FaLightbulb size={20} />,
};